### ISSUE TITLE
Limit Professor Rating Description to 1000 characters

### ISSUE THREAD

**Issue by MikeB1124** [kyeou/CSUN-Dashboard#17]

**Comment by NimaShafie** [comment]
Just tested this, it does appear that the 1000 character limit is in place, however when you post the review with anything over 1000 characters, the review still gets "posted" and a successful posted message appears.

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/69773301/224859214-cc43b697-7fda-4abc-b228-3e51af7d6423.png">

<img width="143" alt="image" src="https://user-images.githubusercontent.com/69773301/224859262-ec6de705-4239-48dd-bf5e-25ca202c04c5.png">

Actual Behavior:
Review appears to post and even shows a successful post message afterward when the post gets denied.

Expected Behavior:
Not allow the user to get past the "POST" button when submitting the review. There should also be a 1000 character limit displaying, it would be even nicer if it were to follow this format:
<img width="310" alt="image" src="https://user-images.githubusercontent.com/69773301/224859511-a2db9c78-3d00-41cd-acd2-d5abe9e776b6.png">

**Comment by NimaShafie** [comment]
Created the new functionality of the character count limiter under the "Write a Review" textbox and set a 1000 character limit
On commit: ea81b74735f9ab1b7d66c1ea93321a0954840e40
